### ISSUE TITLE
Untrusted nodes in raft?

### ISSUE THREAD

**Issue by traverseda** [bakwc/PySyncObj#104]
What would be some problems with just opening a SyncObjServer up to the public internet? Let's say I wanted to create a chat room that anyone could join, and open it up on a p2p vpn like zerotier.

What kind kind of issues would I run into? It looks like the default serializer is pickle, so that's the first issue.

**Comment by bakwc** [comment]
Use encryption. Set `password` to `SyncObjConfig` and install `cryptography` module.

**Comment by traverseda** [comment]
Well there's no way that's all of it, like it looks like it's using pickle for serialization?

Coping from a crypto-currency adjacent background, I had assumed that this implemented [byzantine fault tolerance](http://www.scs.stanford.edu/14au-cs244b/labs/projects/copeland_zhong.pdf), but since that's not the case that would obviously be a first step to allowing random untrusted nodes into a network. Mind if I create an issue for that?
