### ISSUE TITLE
DNS resolve after reboot 

### ISSUE THREAD

**Issue by alexeymyltsev** [bakwc/PySyncObj#119]
After reboot we do  not have ip in cache  and timePassed  < cacheTime in such case we have None as ip and patroni failed to start.
Looks like string [here](https://github.com/bakwc/PySyncObj/blob/792b6112cfa234716f5e0408194114f1abc8b1ad/pysyncobj/dns_resolver.py#L23) should be like this 
`if (timePassed > self.__cacheTime) or (not ips ) or (timePassed > self.__failCacheTime):`

**Comment by bakwc** [comment]
Thanks for report. This check was made to prevent infinite dns server ddos if it fails to return ip. Can you reproduce it on pure syncobj without patroni?

**Comment by bakwc** [comment]
Fixed, please check (uploaded to pip).
`pip install pysyncobj --upgrade`

**Comment by alexeymyltsev** [comment]
Thank you! After upgrade resolve after reboot works  as expected.
