### ISSUE TITLE
Get state utility

### ISSUE THREAD

**Issue by bofm** [bakwc/PySyncObj#136]
I want to implement a utility that is similar to pysyncobj_admin but dumps a ReplDict k-v store to stdout. Could you please suggest on how to better implement it?

**Comment by bakwc** [comment]
1) You need to use "setOnUtilityMessageCallback". You need to make the same method in SyncObj and proxy calls to __transport. Look at:
```
self.__transport.setOnUtilityMessageCallback('status', self._getStatus)
```
2) Inside your KVStorage just write a function getKVState and set is a callback to your new command.
3) Add a new command to syncobj_admin.
