### ISSUE TITLE
PySyncObj on Kubernetes

### ISSUE THREAD

**Issue by schmidtfx** [bakwc/PySyncObj#137]
I want to run PySycnObj on Kubernetes and would like to scale the cluster as I scale the deployment.
Any thoughts how to achieve that?

**Comment by bakwc** [comment]
You can add new nodes online with [syncob_admin](https://github.com/bakwc/PySyncObj/wiki/syncobj_admin#add-new-node) utility.
Just keep in mind that they should be added one by one (waiting while each node be added to cluster), you can't add multiple nodes at the same time.
Same for down-scaling.
