### ISSUE TITLE
question: Check if SyncObj is in sync with the cluster

### ISSUE THREAD

**Issue by bofm** [bakwc/PySyncObj#141]
How to check if the SyncObj instance's state is not stale? In case a cluster looses the majority of it's members the `@replicated` method calls will no longer be replicated. What is the recommended way to detect this?

**Comment by bakwc** [comment]
1) You can add a `callback` parameter and get notifications about success / failed replications.

2) There is a `getStatus` - it returns dict with different information, there is `partner_nodes_count` and `partner_node_status_server_SOME_ADDRESS` with `2` for online nodes and status `0` for offline nodes, you can check that more than a half of nodes are online.

If you have a little time - could you please make method `isMajorityAvailable` with logic described above and send PR?

**Comment by bofm** [comment]
Inside `isMajorityAvailable` should we check only for `self.__connectedNodes` count?

What would be the semantics of isMajorityAvailable? Should it indicate that
1.  _the majority is literally available only_ or
2.  _is current node in sync with the majority_?

I think from the library user perspective 2 has more value. So maybe we should make something like `isInSyncWithMajority` method?

**Comment by bakwc** [comment]
Up to you, `isInSyncWithMajority` is ok.
You should not use `self.__connectedNodes` (it store readonly connections along with cluster participants).
You should iterate over `self.__otherNodes` and check `isConnected` for each node.

**Comment by bofm** [comment]
How to check for that "in sync" thing? Does isConnected imply that the node has approximately the same last applied term?

**Comment by bakwc** [comment]
It's harder to implement. `isNodeConnected` checks that there was some recent responses from this node, doesn't mean that current node received all changes.
To ensure that you have all recent changes you need some time-tick replicated method that will be called on leader, and check that current time not so far from leader setted time.

**Comment by bakwc** [comment]
That can be done as a separate "_battery_" class, eg. StaleWatcher.

**Comment by bofm** [comment]
Hmm, definitely not trivial.

**Comment by bofm** [comment]
### Recap: 

The recommended way to check if the current instance of SyncObj is up-to-date with the cluster is to call a replicated method. If it doesn't time out it means the call has been committed on Raft leader and applied to Raft logs on the majority of the cluster members.

@bakwc 
* Сan you confirm if my understanding (the Recap) is correct?
* I suggest not to add `isMajorityAvailable` method as it may cause a wrong assumption that it checks for the current node cluster sync status (i.e. if the current node is not stale and is up-to-date with the cluster).
* Regarding `isInSyncWithMajority` I don't know how to implement it to be honest. There probably should be a periodic checker for some action. And the check period must somehow depend on the SyncObj config.

**Comment by Jaisinghaa** [comment]
Hi, this is Jaisingh, iam not at all able to understand how to use this package, i just have a mininet topology with three pox controller, and few switches and hosts. but how should i use this package, where to implement, how this actually implimented.
 any info would be fine .

**Comment by bakwc** [comment]
What are you trying to achieve?

**Comment by Jaisinghaa** [comment]
thank you so much for your reply. i am trying to achieve consensus based
fault tolerance in SDN.

**Comment by Jaisinghaa** [comment]
I have selected raft as Consensus algorithm. i do not have any kind of Idea
How i should achieve that. i came to know about pysynobj, but how can i
achieve it. it is a still confusion for me. it would be great if you can
spare some time for me.

**Comment by Jaisinghaa** [comment]
Hi. i have 3 raft controllers running on same machine with 3 diff port, can
i use pysyncobj on these controllers, if yes How?  i tried to run basic
example but that did not work

**Comment by Jaisinghaa** [comment]
pox controllers. not raft

**Comment by bakwc** [comment]
Could you please write the detail commands that you tried?

**Comment by Jaisinghaa** [comment]
i am trying to run basic example. i have three pox SDN controllera running
on a single code(program) . where should i deploye this basic example code.
?. where should i check increment counter value?
i executed hasic example as a python script, but no use. so How i should
move forward with this?

if you have any code previously worked with SDN controllers, it would be
great for me start working on pysyncobj.

**Comment by bakwc** [comment]
Please provide an exact command that you run, the output and what you expected to get.
You need to run at least 3 nodes on different ports or on different machines. It can't work alone and it does not have any sense - the library is made to sync multiple instances, not the single one.

**Comment by bakwc** [comment]
Recently @mcassaniti introduced a new property hasQuorum, it could be used if cluster is online and ready.
