### ISSUE TITLE
syncobj_admin support data query option such as get and list?

### ISSUE THREAD

**Issue by cobolbaby** [bakwc/PySyncObj#145]
Just like etcdctl .

**Comment by bakwc** [comment]
Currently there is no ability to do it. Syncobj (unlike etcd) by itself doesn't store anything. How is it supposed to work?

**Comment by cobolbaby** [comment]
Oh, I had a misunderstanding before. Does this mean that `PySyncObj` only provides the function of file synchronization, and does not care about the content? The synchronized data is completely user-defined.

**Comment by bakwc** [comment]
> Does this mean that PySyncObj only provides the function of file synchronization, and does not care about the content?
Sort of, it provide API for synchronization of state machines (in a simple case - python classes).

**Comment by cobolbaby** [comment]
ok
