### ISSUE TITLE
Support injecting logger to print core logs to help locate the problem

### ISSUE THREAD

**Issue by cobolbaby** [bakwc/PySyncObj#146]

**Comment by bakwc** [comment]
SyncObj currently use `logging` library for logs. You can override logging parameters with `logging.basicConfig`.
Currently there is very few logs, may be we can add more if you describe more specific what are you trying to debug.

**Comment by cobolbaby** [comment]
My idea is to first ensure that the logs are covered when the data synchronization is abnormal.

**Comment by bakwc** [comment]
To debug data synchronization issues - there methods `getStatus` / `printStatus`. They dumps a lot of useful information, eg. `commit_idx` and `last_applied`.
Usually if nodes has simmilar `last_applied` - that means data is in sync.
Currently you need to call them manually on each node (or with syncobj_admin) and check output.
