### ISSUE TITLE
Wrong log output to stdout. May break apps using library.

### ISSUE THREAD

**Issue by Kishi85** [bakwc/PySyncObj#153]
commit fd40b739d6cf12115c103cfb927a2831f673e82d added a print() statement to the disconnect function that always outputs "Disconnect request" to stdout. This can break apps using pysyncobj due to excessive log output in interactive use-cases.

Example: Patroni's edit-config feature spawns vi to edit the config values, which gets totally plastered by above message while the config is edited, making the editing almost impossible due to not being able to see what is actually done.

I propose to change the output from print(...) to using python logging (using level DEBUG?) as it is already used in syncobj.py and this seems to be an oversight from implementing/testing.

**Comment by bakwc** [comment]
Oh, sory, that was not intended to go to production. Removed that print, updated in pip, please update version to 0.3.10.
I will add a unit-test to avoid addint prints in the future, #154

**Comment by Kishi85** [comment]
Thank you, that fixes the issue!
