### ISSUE TITLE
Raft match index is not monotonic

### ISSUE THREAD

**Issue by meteam2022** [bakwc/PySyncObj#167]
## Describe the Bug

There exists an execution that causes `__raftMatchIndex` to be non-monotonic, which violates the raft paper's specification.

## The Relevant Code

The relevant code that will be used later:

1. Sending append entries advances `__raftNextIndex` if `nextNodeIndex <= self.__getCurrentLogIndex()`  (line 1146). Always true if client makes an operation.

https://github.com/bakwc/PySyncObj/blob/d9c2deb7c0403ac26c1cfdcf6e29c9dc0a44e1e4/pysyncobj/syncobj.py#L1144-L1146

2. When Leader receives msg `next_node_idx, success is True`, it sets `__raftMatchIndex` to `nextNodeIdx - 1`, but does not set `__raftNextIndex` (line 960).

https://github.com/bakwc/PySyncObj/blob/d9c2deb7c0403ac26c1cfdcf6e29c9dc0a44e1e4/pysyncobj/syncobj.py#L956-L960

3. When Follower receives msg `append_entries, entries is not []`, it sends msg `next_node_idx, nextNodeIdx=newEntries[-1][1], success=True` to Leader (line 913).

https://github.com/bakwc/PySyncObj/blob/d9c2deb7c0403ac26c1cfdcf6e29c9dc0a44e1e4/pysyncobj/syncobj.py#L909-L913

## The Interleaved Execution

Assume there is a 3-node cluster, and the network has large delay and is easy to disconnect.

We care only the Leader and one of a Follower. (The other follower votes for the Candidate, and it is no longer used.)

`msg ae (entries=[...])` is a message append entries sent by Leader (`entries=[2..5]` means log entries from idx 2 to idx 5). `msg nni=number (reset/success)` is a message next node index sent by Follower. client op is a client operation, which is used to grow the leader's log (such as `ReplDict1.set('key', 'v2')`).

Simplified execution (see the figure below for details):

1. Follower is disconnected from Leader.
2. The first two `msg ae` (become leader, and client op) are not received.
3. Follower is reconnected to Leader.
4. Leader sends two `msg ae` (client op, and send ae) to Follower, which are not successful since Follower has no prev log entries. (Follower replies `msg1 nni=2 reset` and `msg2 nni=2 reset`).
5. Leader receives `msg1 nni=2 reset` and sets `__raftNextIndex=2`.
6. Client op. Leader sends `msg3 ae entries=[2..5]` and sets `__raftNextIndex=6` (according to code `1` line 1146).
7. Follower receives `msg3 ae entries=[2..5]`, and replies `msg4 nni=5 success` (code `3` line 911).
8. Leader sends `msg5 ae entries=[empty]`.
9. Follower receives `msg5 ae entries=[empty]`, and replies `msg6 nni=6 success` (code `3` line 909).
10. Leader receives `msg2 nni=2 reset`, and sets `__raftNextIndex=2`.
11. Leader receives `msg4 nni=5 success`, and sets `__raftMatchIndex=4` (code `2` line 960). Here the **`__raftNextIndex=2` is smaller than `__raftMatchIndex=4`**, which should not appear.
12. Leader sends `msg7 ae entries=[2..5]` because `__raftNextIndex=2`.
13. Follower receives `msg7 ae entries=[2..5]`, and replies `msg8 nni=5 success` (code `3` line 911).
14. Leader receives `msg6 nni=6 success`, and **sets `__raftMatchIndex=5`**.
15. Leader receives `msg8 nni=5 success`, and **sets `__raftMatchIndex=4`** (code `2` line 956 and 960), which violates the monotonicity specification.

![match-index-not-monotonic](https://user-images.githubusercontent.com/118866424/203465219-89884d39-78f6-4369-a59b-2ff1b253f443.png)

## Possible Fixes

Code `1`: Remove line 1146, do not advance next index while sending append entries. However, it changes the logic and may be unsafe, and may affect performance.

Code `2`:

- Insert a line after line 960: `self.__raftNextIndex[node] = nextNodeIdx` to avoid `__raftNextIndex` being smaller than `__raftMatchIndex`.
- Add a condition check, changes `__raftMatchIndex` only `if self.__raftMatchIndex[node] < currentNodeIdx`.

Code `3`: Change line 911 to `nextNodeIdx = newEntries[-1][1] + 1`.

Currently I have not verified the above possible fixes. If some of them are considered good, I will verify them.

**Comment by Sandwichs-del** [comment]
I believe there is another way for this to happen than a slow network: Attacker.
While pysyncobj implements an anti-replay protection via `sendRandKey` and `recvRandKey`, this is good only for new connections. An attacker transparently proxying the TCP connection [can still replay/reorder/drop messages arbitrarily](https://github.com/fernet/spec/issues/27).

Since pysyncobj does not use the `ttl` atribute to `Fernet.decrypt`, any prior message in the same TCP connection could be replayed.

**Comment by bakwc** [comment]
Yeah, sorry for delay, I'll apply fix in the nearest future

**Comment by bakwc** [comment]
According to the raft paper, the nextNode is index of the next entry, and not the last existing entry. So IMO the fix should be the 3-d one:

`nextNodeIdx = newEntries[-1][1] + 1`

Created a PR, #171 

@meteam2022 could you please review / verify a fix?
