### ISSUE TITLE
Keep alive in TCP Connection

### ISSUE THREAD

**Issue by andrewdmit** [bakwc/PySyncObj#172]
Hi,

**Describe the bug**
The Raft cluster consists of three nodes. After the leader is stopped, the remaining followers cannot choose a new leader among themselves. There is network access between the nodes. The lsof command shows the established network connection between the nodes.
At the time of the new leader's election, the network dump between nodes contains only packets retransmits. We assume that the main problem is in our network equipment. 
Most likely our network equipment breaks the socket because followers don't exchange packets with each other, but pysyncobj and the server OS keep the socket logically established. 
It would be great to add TCP keepalive timers on an open socket to pysyncobj to track the network connection, like setsockopt() or something like that.

**Expected behavior**
The availability of a network connection is periodically checked between the followers to election a leader between them.

**Environment**
Patroni version:2.1.4
PostgreSQL version:14.2
DCS (and its version): pure Raft version 0.3.11

**Comment by bakwc** [comment]
Done by #176
