### ISSUE TITLE
Can I know the meaning of this code?

### ISSUE THREAD

**Issue by kbbmanse** [bakwc/PySyncObj#178]
Hi!
I am a beginner who uses pysyncobj.
I'm implementing a distributed processing program using pysyncobj.
I was faced with the problem of not being able to communicate between nodes while distributing the code that works well locally to the actual node environment.

**problematic settings**
my_node: '0.0.0.0:18000'
other_nodes: ['abc-1:18000', 'abc-2:18000']

Node address has been set on the form.

After trying this and that, I changed to my_node: 'abc-0: 18000' and communicated successfully.
I checked the code in debug mode to see why it is not possible to communicate with '0.0.0.0: 18000'

[this code](https://github.com/bakwc/PySyncObj/blob/3ae622afbc92f506820a835a64595db51ba3de1e/pysyncobj/transport.py)

In this code, it seems that my_node can not connect to other_nodes while returning False from 'self._selfNode.address > 
 node.address' .
What does 'self._selfNode.address > node.address' code mean?

thank you.

**Comment by bakwc** [comment]
1) You should use an external address inside my_node settings. If your external address differs from bind address there is a separate settings bind address in settings, you should use this one.
2) The code detects which node should start connection (be a client) and which node should wait connections from others (be a server). Eg. you have nodes:
`nodeA`, `nodeB`, `nodeC`
In this case:
`nodeA` will wait for for connections from `nodeB` and `nodeC` and will not try to connect to any of this nodes itself.
`nodeB` will wait for connections from `nodeC`, but it will try to connect to `nodeA`
`nodeC` will try to connect to `nodeB` and `nodeA`

**Comment by kbbmanse** [comment]
thank you for your answer!

**Comment by kbbmanse** [comment]
> 1. You should use an external address inside my_node settings. If your external address differs from bind address there is a separate settings bind address in settings, you should use this one.
> 2. The code detects which node should start connection (be a client) and which node should wait connections from others (be a server). Eg. you have nodes:
>    `nodeA`, `nodeB`, `nodeC`
>    In this case:
>    `nodeA` will wait for for connections from `nodeB` and `nodeC` and will not try to connect to any of this nodes itself.
>    `nodeB` will wait for connections from `nodeC`, but it will try to connect to `nodeA`
>    `nodeC` will try to connect to `nodeB` and `nodeA`

Okay. I see. Thank you for the details!!
