### ISSUE TITLE
Make callers blocking until command has been accepted by quorum

### ISSUE THREAD

**Issue by schmidtfx** [bakwc/PySyncObj#18]
As far as I understand, the callback mechanism for calls to a replicated method, can be used in order to block until the quorum has accepted the change. As an example, the counter.py code uses the callback mechanism to print the updated value. Furthermore, the callback can also being used to do error handling, e.g. if no leader is present.

Currently, I'm achieving the blocking through the following mechanism:

```python
@replicated
def __setValue(self, key, value):
  self.__data[key] = value

def setValue(self, key, value):
  class local:
    result = None
    error = None
  def set_callback(res, err, event):
    local.result = res
    local.error = err
    event.set()
  event = threading.Event()
  self.__setValue(key, value, callback = partial(set_callback, event = event))
  # wait for the callback to be called
  event.wait()
  # callback has been called - now can do post processing
  return local.result
```

Thinking about making this easier to use, a future-like mechanism would be very helpful. Here is some sample code:

```python
def setValue(self, key, value):
  future = self.__setValue(key, value, waitForQuorum = True)
  res, err = future.get() # potentially blocking call
  return res
```

Furthermore, it would be nice if it could work with aysncio as well, using a generator style in order to avoid having the caller thread blocking all the time:

```python
def setValue(self, key, value):
  yield from self.__setValue(key, value, waitForQuorum = True)
```

**Comment by schmidtfx** [comment]
does async imply any kind of future concept here? Or is it just a blocking call to the replicated function?

**Comment by bakwc** [comment]
I think just blocking would be enough - one async version with callback and one blocking.

**Comment by bakwc** [comment]
P. S. I mean `@replicated-sync` decorator for sync call, typo.

**Comment by schmidtfx** [comment]
How about three things:
1) `@replicated` - behavior as it is today, user can provide callback
2) `@replicated-sync` - blocks until the quorum has accepted the change
3) `@replicated-async` - returns a future

For a starter, the `@replicated-sync` will cleanup my code quite a bit, since it is what it is doing at the moment.

`@replicated-async` will be quite handy in order to increase throughput, e.g. requests/second.

**Comment by bakwc** [comment]
Good. Would you like to implement it?

**Comment by schmidtfx** [comment]
So for the replicated-sync, how about just using my code? I can come up with a pull request.

**Comment by schmidtfx** [comment]
Can you assign the issue to me?

**Comment by bakwc** [comment]
Yep, accept contributor invite.

**Comment by schmidtfx** [comment]
Merged into master
