### ISSUE TITLE
Question: Does Lock in batteries support leader crash?

### ISSUE THREAD

**Issue by foxleren** [bakwc/PySyncObj#183]
Hi! I tried to use `ReplLockManager` as it is shown in project README.md, but I noticed that follower can't acquire Lock after leader crash and just freezes. Is it implemented in batteries?

**Comment by bakwc** [comment]
There is a configurable timeout for auto-expire to handle cases like this, called `autoUnlockTime` - it's the first and the single argument of ReplLockManager. In the readme it's set to 75 seconds. That mean that after 75 seconds lock will be unlocked.
