### ISSUE TITLE
Add git revision to debug info

### ISSUE THREAD

**Issue by bakwc** [bakwc/PySyncObj#19]
SyncObj has function _printStatus(), it would be good to have version and revision information there.

**Comment by schmidtfx** [comment]
How do you envision it? This might only work if you run it from within a git repo, right? What do you expect if someone executes it outside of a git repo?

**Comment by bakwc** [comment]
Pre-commit hook should generate version.py

**Comment by bakwc** [comment]
Added in 6c6d14b2a01b, 6c6d14b2a01b7ebdc.
