### ISSUE TITLE
Improve command apply time

### ISSUE THREAD

**Issue by bakwc** [bakwc/PySyncObj#34]
Currently we have long delay between time when command request received and time when it's applied to cluster (~0.4 seconds, according to benchmakrs in https://github.com/GianlucaBortoli/krafters). Need to write a delay benchmark and optimize delay.

**Comment by schmidtfx** [comment]
What's is the delay now?

**Comment by bakwc** [comment]
~0.01 seconds at 50rps. Benchmark can be launched by:

    cd PySyncObj/benchmarks
    python benchmarks.py delay

**Comment by bakwc** [comment]
Also you need to set `appendEntriesUseBatch=False`, by default syncobj is optimized for max requests per second and not for delay.
