### ISSUE TITLE
Cannot detect tcp address is in use.

### ISSUE THREAD

**Issue by kevenli** [bakwc/PySyncObj#45]
The syncobj constructor just start an async thread to poll starting tcp server, and if the tcp port is in use, it just loop forever. 

Since in my project, I want to start a cluster (forked processes) in a daemon process, I want them pick propriate port to use automatically, I need an exception if creating tcpserver with problem, so the node may know it should switch to another port.

I wonder if you are going to support this.
Thank you for this wonderful project.

**Comment by bakwc** [comment]
Sure, I can add a function `waitBind()`, and a `bindRetryNumber` config option. So you'll be able to set `bindRetryNumber` to 1, and call `waitBind` after creation of the object. `waitBind()`will blocks untill port successfully binded or `bindRetryNumber` of failures will be reached. In that case an `waitBind()` will raise an exception. Is that ok?

**Comment by bakwc** [comment]
BTW, for your task it may be a better solution to select appropriate ports in a parent process and pass them to a child one.

**Comment by kevenli** [comment]
Thanks, that's good for me.

**Comment by bakwc** [comment]
You can try now, set `maxBindRetries` to `1` and call `waitBinded` after creation of your object.
