### ISSUE TITLE
Not possible to mix nodes with In-memory and File serializers...

### ISSUE THREAD

**Issue by CyberDem0n** [bakwc/PySyncObj#48]
It happens due to some incompatibility between zlib and gzip.
I think it make sense to unify compression algorithm, i.e. either use zlib or gzip when doing serialization during log compaction.
Not sure whether it is a bug or feature though.

I can prepare a fix if you want.

**Comment by bakwc** [comment]
Yep, it would be great!

**Comment by bakwc** [comment]
Also please look at #15, may be you'll be able to fix that too.

**Comment by CyberDem0n** [comment]
Here we go: https://github.com/bakwc/PySyncObj/pull/49
What is the use-case for #15 ?

**Comment by bakwc** [comment]
For example, we have a cluster with in-memory serialization and we decided to switch to a disk one. We don't want to stop the whole cluster for that.

**Comment by CyberDem0n** [comment]
With PR #49 you can restart nodes one-by-one

**Comment by bakwc** [comment]
Part of nodes can be with disk serialization and another part with in-memory?

**Comment by CyberDem0n** [comment]
> Part of nodes can be with disk serialization and another part with in-memory?

Yep

**Comment by bakwc** [comment]
Great, that's enough.
