### ISSUE TITLE
if a read after a wirte,how can we know the data we read is already updated by write

### ISSUE THREAD

**Issue by heiwhite** [bakwc/PySyncObj#5]

**Comment by bakwc** [comment]
What do you mean? If we read **after** write - we will get already updated data.

If you want to know about any changes of your data - just add a callback to a constructor of your replicated class, store it and call it each time the data updated - it will be called on all servers.

If you implement a counter like a class with getCounter and setCounter - yep, there could be a problem that if you want to increment counter by one, you read it, and someone read after it, and then you write incremented value, and someone write incremented value, and you got a bug that value incremented only once. In this case you should make all your operations atomic (transaction / etc.). You just implement incrementCounter that will increment your counter in a single method.

For different tasks there are diferent ways to make atomic operations. For example - tryAcquire for a mutex (it will check if mutex is already locked, and if not - it will lock it). Or compare-and-swap. Or add revision to your data, pass revision to a write operation and fail a write operation if your data have wrong revision.

Please tell more about your case and I'll try to give some advice.

**Comment by heiwhite** [comment]
thank you for your answer
