### ISSUE TITLE
Вопросы по использованию библиотеки

### ISSUE THREAD

**Issue by mentalMedley** [bakwc/PySyncObj#52]
Здравствуйте. Я пытаюсь разобраться с использованием проекта на Ваших примерах. Не могли бы Вы прояснить некоторые моменты использования библиотеки:

1. Как я понял из исходников синхронизация обеспечивается вызовом на всех нодах одинаковых методов с одинаковыми параметрами. Как в таком случае решается проблема начального состояния динамически добавленной ноды. Т.е. если в примере со счетчиком досчитать к примеру до 42, а затем подключить новую ноду, то какое значение счетчика будет на новой ноде - 0 или 42? Если 42, то как она об этом узнает?

2. В примере kvstorage_http.py я не смог решить проблему: если поднять обе ноды, а затем одну погасить, то при добавлении нового значения оно не будет добавлено в хранилище (что логично), но при этом клиенту отдается ответ 201 Created, хотя по логике код ответа должен быть из серии 50Х. Я попытался применить к методам другой декоратор вместо replicated поставить replicated_sync, но получил ошибку:
```
Traceback (most recent call last):
  File "kvstorage_http.py", line 13, in <module>
    class KVStorage(SyncObj):
  File "kvstorage_http.py", line 21, in KVStorage
    @replicated_sync
NameError: name 'replicated_sync' is not defined
```
Правильно ли я применил декоратор?
```
class TestObj(SyncObj):

    def __init__(self, selfNodeAddr, otherNodeAddrs):
        super(TestObj, self).__init__(selfNodeAddr, otherNodeAddrs)
        self.__counter = 0

    @replicated_sync
    def incCounter(self):
        self.__counter += 1
        return self.__counter

    @replicated_sync
    def addValue(self, value, cn):
        self.__counter += value
        return self.__counter, cn

    def getCounter(self):
        return self.__counter
```
Подскажите use case как узнать приняла ли нода переданное ей изменение.

3. Как определить доступность кворума? Я нашел функцию isReady, которая отвечает синхронизирована ли нода. Но как узнать синхронизированы ли более (N + 1) / 2 всех нод кластера, т.е. доступен ли кворум? В примере lock.py не совсем понятно как достигается гарантия блокировки в методе acquire. Вызывая этот метод, если клиент получает True, он полагает, что ресурс заблокирован. Но когда кворум недоступен, acquire не реплицируется на кластер и клиент не узнает об этом (вызов же асинхронный), т.е. получается он ошибочно считает, что владеет ресурсом?

Заранее спасибо за помощь.

**Comment by bakwc** [comment]
1. Синхронизация достигается с использованием двух механизмов - журнала транзакций и полной сериализации объекта при заполнении журнала. Каждая команда пишется в журнал. Этот журнал синхронизируется между узлами целиком. Соответственно когда включается новый узел, он получит журнал всех старых операций и по очереди применит их у себя. Таким образом значение счетчика будет 42.

2. В примере сделана простая схема, которая не дожидается реальной записи данных. Дождаться подтверждения можно используя декоратор replicated_sync (блокируется), или передавая callback (асинхронно). Декоратор надо тоже импортировать (from pysyncobj import replicated_sync). Использование правильное. В случае ошибки произойдет exception.

3. Например сделать какой-то запрос, если он зафейлится с таймаутом, значит кворума нет. Готовой функции проверить есть ли кворум не существует, так как наличие кворума проверяется для каждого из запросов независимо.
В случае с lock при отсуствтии кворума функция acquire зафейлится (из за отсутствия соединения с лидером или по таймауту). В примере клиент пробует взять лок (tryAcquireLock), а потом проверяет через isAcquired взят ли он или нет. Можно слегка переделать пример, поменяв на replicated_sync и дожидаясь ответа.
