### ISSUE TITLE
Windows compatibility?

### ISSUE THREAD

**Issue by steve-bate** [bakwc/PySyncObj#63]
The documentation says the library is supported on Windows, but when I try to install PySyncObj on Windows (Python 2.7.x) I see the following error:

```
      . . .
      File "pysyncobj\__init__.py", line 1, in <module>
        from .syncobj import SyncObj, SyncObjException, SyncObjConf, replicated, replicated_sync,\
      File "pysyncobj\syncobj.py", line 29, in <module>
        from .pipe_notifier import PipeNotifier
      File "pysyncobj\pipe_notifier.py", line 2, in <module>
        import fcntl
    ImportError: No module named fcntl
```

My understanding is that fcntl is only supported on Unix-like platforms.

**Comment by bakwc** [comment]
Thanks for report! Will fix it tomorrow. Currently we don't have CI for windows, seems like windows support was broken few versions ago.

**Comment by bakwc** [comment]
Released a new version with repaired windows support. You can update with `pip install pysyncobj -U`
