### ISSUE TITLE
Cluster of machines on different networks

### ISSUE THREAD

**Issue by ch3njust1n** [bakwc/PySyncObj#66]
How would I use this to create clusters with machines on different networks? Like for the counter.py example, I'd like to do something `python counter.py localhost:8080 123.123.123.123:8080` Also how can I use this to create and join arbitrary clusters?

**Comment by bakwc** [comment]
> How would I use this to create clusters with machines on different networks?

You can specify arbitrary ip / hostname. Of course, this ip / hostname should be accessable from any machine of your cluster.

> Also how can I use this to create and join arbitrary clusters?

What do you mean? Just start all your nodes, and specify other node addresses - they will connect to each other automatically.

**Comment by ch3njust1n** [comment]
Thanks for responding so quickly.
To clarify my second question: say I have 10 different machines and each machine knows the ip and ports for all other machines. At random times, I would like them to form random clusters of 3 machines and perform some computation. Is that possible to continuously form random clusters and how would I do this?

**Comment by bakwc** [comment]
Soultion 1: you can generate random clusters by using the same seed on all machines. This will guarantee that they will be the same.
Solution 2: you create a single cluster, but inside that single cluster you create random subclasters each time you need.

**Comment by ch3njust1n** [comment]
Ah I see. Could you give an example or some more detail on how to do your second suggestion?

**Comment by bakwc** [comment]
For example - you can use ReplQueue battery for sending job and receiving result. So you split your job into N parts (where N - number of nodes in your new subcluster), send them to one repl queue. Each node tries to extract task from queue, eg once per second - executes it and returns result into other queue.
