### ISSUE TITLE
Pre-configured cluster with a single node start

### ISSUE THREAD

**Issue by SantjagoCorkez** [bakwc/PySyncObj#71]
Having a config where we start a cluster node-by-node (or, for example, one node succeeded to start, others failed) we need to configure SyncObj in such a way that it knows all the nodes at the start time. But in case only one node has started it does not fallback to single-node cluster. How to enforce it in case `__raftNextIndex` is not empty?

Examples:
This is a `getState()` output after 10 second of a node's operation in case another node was pre-configured at startup (127.0.0.1:9001)
```
{
  "version": "0.3.3",
  "revision": "1899fe752bde334787dbfa54bb51bbd9fcf2826c",
  "self": "127.0.0.1:9000",
  "state": 0,
  "leader": null,
  "partner_nodes_count": 1,
  "partner_node_status_server_127.0.0.1:9001": 0,
  "readonly_nodes_count": 0,
  "unknown_connections_count": 0,
  "log_len": 1,
  "last_applied": 1,
  "commit_idx": 1,
  "raft_term": 0,
  "next_node_idx_count": 1,
  "next_node_idx_server_127.0.0.1:9001": 2,
  "match_idx_count": 1,
  "match_idx_server_127.0.0.1:9001": 0,
  "leader_commit_idx": null,
  "uptime": 10,
  "self_code_version": 0,
  "enabled_code_version": 0
}
```

And this is the same 10-seconds later snapshot but initial nodes config was empty at startup
```
{
  "version": "0.3.3",
  "revision": "1899fe752bde334787dbfa54bb51bbd9fcf2826c",
  "self": "127.0.0.1:9000",
  "state": 2,
  "leader": "127.0.0.1:9000",
  "partner_nodes_count": 0,
  "readonly_nodes_count": 0,
  "unknown_connections_count": 0,
  "log_len": 2,
  "last_applied": 2,
  "commit_idx": 2,
  "raft_term": 1,
  "next_node_idx_count": 0,
  "match_idx_count": 0,
  "leader_commit_idx": 2,
  "uptime": 10,
  "self_code_version": 0,
  "enabled_code_version": 0
}
```

As you can see the second case leads to successful leadership acquisition as there's no other nodes to connect and produce formal election procedure with.

How could one force a node to fallback to single-cluster mechanics in case other configured nodes are unable to connect to?

**Comment by bakwc** [comment]
There is two possible scenarios:

1. One node started and second node has not.
2. Both nodes started but there is a problem with connection between them.

We can't detect which scenario we have. For the second one - each node will think that the other node has not started and we will get unconsistent state.
