### ISSUE TITLE
how to scale with the log

### ISSUE THREAD

**Issue by chillancezen** [bakwc/PySyncObj#73]
hi experts,
as far as I know from experiment,  when not set conf.journalfile, the log records are kept in memory, and when peers restart, they are synchronized with peers to recover.

so could I clean the logs periodically in case they are getting too large

regards
Jie

**Comment by chillancezen** [comment]
as complementary words, I need to synchronize lots of objects and objects using SyncObj, I am so worried I will encounter performance degradation.

**Comment by bakwc** [comment]
There is no need to clean logs manually, it's done automatically. This is configured by config options `logCompactionMinEntries` and `logCompactionMinTime`. By default - logs will be cleared every 5000 operations or every 300 seconds (whichever comes first).

**Comment by chillancezen** [comment]
thanks alot
