### ISSUE TITLE
multithread issue

### ISSUE THREAD

**Issue by chillancezen** [bakwc/PySyncObj#74]
hi bakwc, 
could you please help me with the questions below:
1.is the 'replicated' decorated function  thread safe, i.e. can it be shared among threads?
2.if syncobj is in async mode(callback is set), could I detect the timeout in someway?
3. if I call A() in sync mode, and call A() in async mode within another thread, do these two invocations conflict,

regards
Jie

**Comment by bakwc** [comment]
> 1.is the 'replicated' decorated function thread safe, i.e. can it be shared among threads?

You can **call** a function with `replicated` decorator from any thread - **call** is thread safe. But all your calls will be really executed in a special separate thread (which is created by syncobj automatically). So if you modifying some outer state from you function and from your main thread (or any other) both - you should protect it with mutex.

> 2.if syncobj is in async mode(callback is set), could I detect the timeout in someway?

No, currently timeouts works only in sync mode, added separate issue for adding timeouts for async mode, #75

> 3. if I call A() in sync mode, and call A() in async mode within another thread, do these two invocations conflict

No conflicts, it's a valid scenario

**Comment by chillancezen** [comment]
toooooo much thanks ~
