### ISSUE TITLE
recursively calling replicated method.

### ISSUE THREAD

**Issue by chillancezen** [bakwc/PySyncObj#76]
hi bakwc,
could you help me with two more PRs below:
1.could I call the replicated and nested method?i.e.
@replicated 
def A():
     B()
@replicated 
def B():
     pass
is this legitimate ?
2.how could I get info about the callback and whether it's a synchronous invocation inside a @replicated  decorated method? is it possible to do that?

regards
Jie

**Comment by bakwc** [comment]
1. You should pass `_doApply=True` if you call one replicated method from another.
```python
@replicated
def A():
    B(_doApply=True)

@replicated
def B():
    pass
```
2. Currently replicated functions does not know anything about callbacks. You can pass aditional argument with this information.

**Comment by chillancezen** [comment]
thanks a lot again~~
