### ISSUE TITLE
You need at least 1 partner to be able to reflect changes?

### ISSUE THREAD

**Issue by xmonader** [bakwc/PySyncObj#77]
started the counter example on 1 node and the other nodes didn't join and the value is always 0 until a partner joins? Is that by design?

**Comment by bakwc** [comment]
If you create a two-node cluster - you need both two nodes to be alive.
If you start from a single-node cluster - you can add second node with syncobj_admin, see [Dynamic-membership-change](https://github.com/bakwc/PySyncObj/wiki/Dynamic-membership-change) and [syncobj_admin](https://github.com/bakwc/PySyncObj/wiki/syncobj_admin).

**Comment by xmonader** [comment]
This is perfect thanks! please feel free to close the issue.
