### ISSUE TITLE
Cannot Create Leader

### ISSUE THREAD

**Issue by zaiweizhang** [bakwc/PySyncObj#79]
Hi bakwc,

This may be a stupid question but I have been stuck on this for some time:
I am trying to run the example counter.py.
I am using self_port: localhost:4000
and partner port: localhost:4001 localhost:4002 localhost:4003

However, when I ran the code, it stuck at leader selection part.
When I ran o._getLeader(), it keeps giving me None.

Do you know what's happening here? 

Thanks a ton

**Comment by bakwc** [comment]
You need to launch 3 more instances of counter.py, leader will not be selected untill half of the cluster is up.

**Comment by zaiweizhang** [comment]
Thank you!
