### ISSUE TITLE
onTick example

### ISSUE THREAD

**Issue by vganapathy-lifesize** [bakwc/PySyncObj#80]
Is there an example I can refer to for application provided event loop (onTick). I am writing an application based on pysyncobj which uses asyncio heavily. Letting pysyncobj seems to create synchronization issues. Was just wondering if I can make use of the existing event loop to trigger ontick. Is there an example I can refer to.

Should I be using async replication incase I have a single event loop. I think so

**Comment by bakwc** [comment]
Yep, it's quite easy:
1) set `autoTick` to `False` in `SyncObjConf`
2) call `syncObj.doTick()` every N times per second (default is 20 times per second)

> Should I be using async replication incase I have a single event loop. I think so

Yep, otherwise you'll get a deadlock

**Comment by bakwc** [comment]
> Letting pysyncobj seems to create synchronization issues.

Another solution - leave autoTick but use async operations and mutex in callback - that should prevent synchronization issues.

**Comment by vganapathy-lifesize** [comment]
Awesome thank you. I thought about using mutexes but I would avoid if I can. I will give single event loop a try. Incase I run into any issues I shall get back.

Just to confirm, in my case I will need to pass the timeToWait as 0 in doTick. Is that correct?

**Comment by vganapathy-lifesize** [comment]
It works fine with single event loop and async replication. Closing the ticket. Thanks a lot @bakwc. Appreciate your help.
