### ISSUE TITLE
Broken git revision number/commit ID in debugging info and pysyncobj.revision.REVISION

### ISSUE THREAD

**Issue by JustAnotherArchivist** [bakwc/PySyncObj#83]
While working on the networking, I noticed the `revision` thing (#19) and looked into it a bit. It seems to be broken, and I'd suggest removing it.

First, a few words in general about doing this. Since the commit ID is determined in part by the commit's contents, it is impossible to include the commit ID in the commit itself. As far as I can see, `pysyncobj/revision.py` always contains the ID of the *previous* commit, i.e. it is always outdated by one commit (see below for comments on the actual implementation). Because one commit can have many child commits, it is therefore not possible to know the state of the code based on the revision number: someone might be using a different branch or their own fork. As an additional complication, there may be uncommitted changes in the repository (e.g. when testing new code).

But even if it were correct, I'm not convinced it's useful either. In general, there are two groups of people who might work with a code: developers and users. Developers basically always need to be aware of what code they're working with anyway, or they know how to check with `git status`, `git log -1`, etc. On the other hand, users should normally only use versioned releases, not a git branch or a specific commit, since that's what you get when you `pip install package`; if they do use the git repository, they either know what they're doing or are developers.

You could make the revision information work correctly when PySyncObj is used directly from the git repository (i.e. when you `git clone` the repo and then use `python setup.py develop` or similar). PySyncObj could detect that its parent directory is a git repository and use `git rev-parse` to retrieve the commit ID. There are also ways to expose whether the repository has uncommitted changes.   
I had to do that before. It works. I still don't think it's a good idea though.

---

As for the actual implementation: I noticed that you use a pre-commit hook to write the commit ID (of the previous commit, not the current one, obviously) to `pysyncobj/revision.py`. In a post-commit hook, you then use `git commit -a --amend` to add and commit this file. The file still contains the previous commit ID though.

There are two issues with this:
1. It uses the commit ID of the previous commit. For example, master's `revision.py` currently (commit 89c9297c) points to 2c8a3263, which doesn't have the test skip for Travis, i.e. does not represent the code of commit 89c9297c.
2. The commit in `revision.py` might not even exist anymore! For example, when you run the code after commit 9b42e6b7 (where you added IPv6 support), `pysyncobj.revision.REVISION` points to the inexistent commit c6979dfc. I think this happens whenever you use something that rewrites the last commit, e.g. amending, rebasing, or squashing. (Note that the local git repository will still hold the orphaned commit for a while until git runs the garbage collection. For similar reasons, GitHub still has that commit, but a fresh clone does not contain it.)

It's possible to work around the first issue by running `generate.sh` in the post-commit hook. The file would then contain the commit ID of the intermediate commit (the `HEAD` at the time post-commit runs). But that intermediate commit won't be referenced anymore after `git commit --amend` and will therefore disappear eventually, i.e. the second issue still exists.

As a sidenote, committing with the hooks will always commit *all* uncommited changes in the repository due to `-a` in the post-commit hook, so it's impossible to make selective commits. This could easily be fixed though by using an explicit `git add` on `revision.py` instead of `git commit -a` in the post-commit hook.

**Comment by bakwc** [comment]
Agree, removed by #115
